"""add_chart_engine

Revision ID: 13ca700b24e2
Revises: 046cb63a4a55
Create Date: 2026-03-17 19:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ca700b24e2'
down_revision: Union[str, None] = '046cb63a4a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_jobs', 'complexity_index',
               existing_type=sa.Float(),
               nullable=False)
    op.alter_column('analysis_jobs', 'total_pills',
               existing_type=sa.Integer(),
               nullable=False)
    op.add_column('analysis_results', sa.Column('chart_engine', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('company_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'company_profile')
    op.drop_column('analysis_results', 'chart_engine')
    op.alter_column('analysis_jobs', 'total_pills',
               existing_type=sa.Integer(),
               nullable=True)
    op.alter_column('analysis_jobs', 'complexity_index',
               existing_type=sa.Float(),
               nullable=True)
    # ### end Alembic commands ###
