"""add vision 2026 orchestration fields

Revision ID: 38be3fc64929
Revises: 25aecfac38e9
Create Date: 2026-03-23 19:15:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '38be3fc64929'
down_revision: Union[str, None] = '25aecfac38e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('required_pillars', sa.JSON(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('synthesis_report', sa.Text(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('multi_source_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'multi_source_ids')
    op.drop_column('analysis_jobs', 'synthesis_report')
    op.drop_column('analysis_jobs', 'required_pillars')
    # ### end Alembic commands ###
